name: Pipeline CI/CD Backend-api

on:
  push:
    branches:
      - main

env:
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/api-backend
  PROJECT_PATH: /home/user/fullstack-devops-app/backend/dev
  DOCKER_SERVICE: backend-api

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

  build-docker-image:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:${{env.BUILD_NUMBER}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}

      - name: Push tagged Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{env.BUILD_NUMBER}}

  deploy:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ env.PROJECT_PATH }}
            sudo docker compose pull ${{ env.DOCKER_SERVICE }}
            sudo docker compose up -d --force-recreate ${{ env.DOCKER_SERVICE }}
