name: Pipeline CI/CD Backend-api

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
