name: Pipeline CI/CD Backend-api

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

  build-docker-image:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t moahemdtaher/api-backend .

      - name: Tag Docker image
        run: docker tag moahemdtaher/api-backend moahemdtaher/api-backend:${{github.run_number}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push moahemdtaher/api-backend

      - name: Push tagged Docker image to Docker Hub
        run: docker push moahemdtaher/api-backend:${{github.run_number}}

  deploy:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/user/fullstasck-devops-app/backend/dev
            sudo docker compose up -d --force-recreate --pull always
